### PR TITLE
feat(docker): add dockerfile

### PR DESCRIPTION
**Pull request by nessex**
Thanks for this project! It's exactly what I was hoping to find for really simple static sites and single page apps!

---

This PR adds a Dockerfile that can be used to deploy SPAs or static sites to Docker / Kubernetes. Expects SPA / static site content to be included in the `/app/` directory.

Notes:
 - Statically builds microserver with musl as the resulting binary is more portable
 - Uses [Distroless](https://github.com/GoogleContainerTools/distroless) to keep the base image small (~20MB total)
 - Uses [tini](https://github.com/krallin/tini) to ensure that the container shuts down quickly and cleanly (proper signal handling) in Kubernetes
 - Uses non-root user in the container for the sake of security

### Intended Usage
With a Dockerfile like the following:
```dockerfile
FROM nessex/microserver:release-v0.1.6
COPY public/ /app/
```

You can run your SPA / static site using:
```bash
$ docker build -t my-service:local .
$ docker run -p 9090:9090 my-service:local
MicroServer running on port 9090!
Serving /app
Spa support: true. Root: index.html
```

Alternatively, you could mount a volume with your content:
```
$ docker run -p 9090:9090 -v $(pwd)/public:/app nessex/microserver:release-v0.1.6
```

More complex Dockerfile usage example with a multi-stage build of a React SPA:
```
FROM node:10.18-stretch-slim as builder
WORKDIR /app
COPY ./ /app
RUN yarn
RUN yarn build


FROM nessex/microserver:release-v0.1.6
COPY --from=builder /app/public /app/
```

### Extra Steps Required
This would work best with an automated build configured through Docker hub. https://hub.docker.com

To test this Dockerfile, I created a repository at https://hub.docker.com/r/nessex/microserver with the following automated build config (to match your existing release tags):

Screen Shot 2020-01-22 at 17 36 21

If you are interested in this PR, and want to create a repository e.g. `robertohuertasm/microserver`, I can add some instructions to `README.md` for using the built images.

### CODE REVIEW

**Comment by robertohuertasm** [comment]
Hi @Nessex, thanks for the PR! ❤️  I'll take a look at it during the weekend!

**Comment by robertohuertasm** [comment]
Hi @Nessex, I've slightly changed some things. Feel free to comment what you think. 

I've used ` ekidd/rust-musl-builder` and instead of installing a hardcoded version, I think it's better to build the repo. By doing this we'll always get the latest version.

I've also created the repo in `Docker Hub` and updated a little bit the readme with the comments you left in this PR's description. Feel free to modify them.

**Comment by robertohuertasm** [comment]
@Nessex let me know if you're ok with the changes and I will proceed to merge it.

**Comment by nessex** [comment]
@robertohuertasm thank you for taking a look! The changes look great, have confirmed they work for me as well.

I think it's ready to go. Just made one really tiny change to the documentation.

**Review by robertohuertasm — APPROVED** [review]
LGTM 🚀

**Pull request merged**
